version: "3"

services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server
    healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
        interval: 5s
        timeout: 5s
        retries: 5

  backend:
    container_name: backend
    build: ./datas/backend/
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - backend-data:/usr/src/app/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - server
        
  nginx:
    container_name: nginx
    build: ./datas/nginx/
    ports:
      - "8483:8483"
      - "8443:8443"
    volumes:
      - logs-data:/var/log/nginx/
    depends_on:
      - backend
      - frontend
    networks:
      - server
  
  frontend:
    container_name: frontend
    env_file: .env
    build: datas/frontend/
    expose:
      - "3000"
    volumes:
      - frontend-data:/home/node/app/
    networks:
      - server

volumes:
  logs-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DATA_FOLDER}/logs"
  frontend-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DATA_FOLDER}/frontend"
  backend-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DATA_FOLDER}/backend"
  db-data:

networks:
  server:
