# Generated by Django 4.2.3 on 2024-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='code',
            new_name='code_name',
        ),
        migrations.AddField(
            model_name='notification',
            name='code_value',
            field=models.IntegerField(default=0),
        ),
    ]
