# Generated by Django 4.2.3 on 2024-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0002_rename_code_notification_code_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=800),
        ),
    ]
